set shell                          := ["bash", "-c"]
set dotenv-load                    := true

@_help:
    just --list --unsorted --list-heading $'🏵  Commands:\n';

test:
    npm i --no-save --only=production ../
    @# Compile to test, not very good
    ../node_modules/typescript/bin/tsc --project tsconfig.json
