set shell                          := ["bash", "-c"]

@_help:
    just --list --unsorted --list-heading $'🏵  Commands:\n';

test:
    # cd .. && npm link
    npm i --no-save --only=production ../
    # npm link @metapages/metaframe-tensorflow-1d
    @# Compile to test, not very good
    ../node_modules/typescript/bin/tsc --project tsconfig.json
    # npm unlink @metapages/metaframe-tensorflow-1d
    # cd .. && npm unlink
