set shell                          := ["bash", "-c"]

@_help:
    just --list --unsorted --list-heading $'🏵  Commands:\n';

_init:
    npm i
    npm link metaframe-predictor-conv-1d-net

test: _init
    @# Compile to test, not very good
    ./node_modules/typescript/bin/tsc
